apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dep
  namespace: flask-app-ns
  labels:
    app: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app


    spec:
      imagePullSecrets:
        - name: ecr-image-secret
      containers:
        - name: flask-app-cont
          image: 705307574472.dkr.ecr.us-east-1.amazonaws.com/flask-app-ecr:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-app-config
            - secretRef:
                name: flask-app-secret